services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - appnet

  streamlit:
    build:
      context: ./app
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api
    env_file:
      - .env
    networks:
      - appnet

networks:
  appnet:
