# Usa imagem oficial do Python
FROM python:3.11-slim

WORKDIR /app

# Copia apenas o que é necessário
COPY requirements.txt ./
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Copia o restante do projeto, incluindo .env
COPY . .

# Expõe a porta do Streamlit
EXPOSE 8501

# Comando para iniciar a interface
CMD ["streamlit", "run", "app/dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]